# Generated by Django 5.2.13 on 2026-04-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("ingredients", models.TextField()),
                ("directions", models.TextField()),
                ("link", models.URLField(blank=True, default="", max_length=255)),
                ("source", models.TextField(blank=True, default="")),
                ("ner", models.JSONField(default=list)),
                ("tokens", models.JSONField(default=list)),
            ],
        ),
    ]
