# Generated by Django 6.0.4 on 2026-04-17 22:38

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0002_recipe_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=300, null=True
            ),
        ),
    ]
